import { Animal, ShelterInfo } from './types';

export const SHELTER_INFO: ShelterInfo = {
  name: "Paws & Home SG",
  tagline: "Every Singapore stray deserves a safe porch and a gentle hand.",
  vision: "We bridge the gap between Singapore's back-alley rescues and loving first-time adopters with compassionate shelter care, patient matching, and dedicated lifelong aftercare.",
  stats: "Community stray welfare and adoption matching initiative across Singapore.",
  address: "71 Pasir Ris Farmway 1, Singapore 519344",
  hours: "Sat & Sun: 10:30am - 5:30pm (By appointment)",
  helpline: "+65 6789 2024",
  activeCount: 8,
};

export const ANIMALS: Animal[] = [
  {
    id: "kopi",
    name: "Kopi",
    age: "1.5 years old",
    category: "Singapore Special",
    story: "Found hiding under a void deck bicycle rack in Bedok during monsoon season, soaking wet and nervous. Now a calm cuddlebug who loves chin scratches.",
    image: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&q=85",
    vaccinated: true,
    dewormed: true,
    gender: "Male",
    size: "Medium (16kg)",
    temperament: "Gentle & Affectionate",
  },
  {
    id: "milo",
    name: "Milo",
    age: "9 months old",
    category: "Domestic Shorthair",
    story: "Spotted by cleaners foraging by an industrial food court in Tuas. Extremely gentle, purrs instantly upon human eye contact, and adores window naps.",
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=85",
    vaccinated: true,
    dewormed: true,
    gender: "Male",
    size: "Small (3.8kg)",
    temperament: "Playful & Purr machine",
  },
  {
    id: "kaya",
    name: "Kaya",
    age: "2 years old",
    category: "Singapore Special",
    story: "Rescued wandering with a limping paw near Kranji agricultural belt. Fully rehabilitated, microchipped, and loves leisurely evening park connector trots.",
    image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=800&q=85",
    vaccinated: true,
    dewormed: true,
    gender: "Female",
    size: "Medium (14kg)",
    temperament: "Loyal & Chill",
  },
  {
    id: "pandan",
    name: "Pandan",
    age: "1 year old",
    category: "Tabby Cross",
    story: "Found quietly roosting atop an aircon compressor unit in Tiong Bahru back alleys. Soft-spoken, clean habits, and perfect for calm indoor apartments.",
    image: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=800&q=85",
    vaccinated: true,
    dewormed: true,
    gender: "Female",
    size: "Small (3.2kg)",
    temperament: "Quiet observer & Sweet",
  },
  {
    id: "teh-o",
    name: "Teh-O",
    age: "3 years old",
    category: "Hound Mix",
    story: "A loyal trail wanderer found near Sungei Tengah farmways. Patient, highly food-motivated, walks beautifully on a loose leash, and loves belly rubs.",
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=800&q=85",
    vaccinated: true,
    dewormed: true,
    gender: "Male",
    size: "Medium-Large (18kg)",
    temperament: "Calm leash buddy",
  },
  {
    id: "tofu",
    name: "Tofu",
    age: "7 months old",
    category: "Calico Cat",
    story: "Discovered sheltering inside an abandoned flower nursery in Lim Chu Kang. Playful, inquisitive, loves chasing paper balls, and gets along well with quiet spaces.",
    image: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=800&q=85",
    vaccinated: true,
    dewormed: true,
    gender: "Female",
    size: "Kitten (2.7kg)",
    temperament: "Curious Explorer",
  },
  {
    id: "chili",
    name: "Chilli",
    age: "2.5 years old",
    category: "Singapore Special",
    story: "Found lingering near a Pasir Ris carpark bin center. Confident with humans, respectful of personal boundaries, and eager to learn household routines.",
    image: "https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=800&q=85",
    vaccinated: true,
    dewormed: true,
    gender: "Male",
    size: "Medium (17kg)",
    temperament: "Friendly & Attentive",
  },
  {
    id: "sesame",
    name: "Sesame",
    age: "4 years old",
    category: "Tuxedo Cat",
    story: "A gentle neighborhood stray from Geylang Bahru displaced by construction. Very serene temperament, quiet companion who loves sleeping at desk corners.",
    image: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=800&q=85",
    vaccinated: true,
    dewormed: true,
    gender: "Male",
    size: "Adult (4.6kg)",
    temperament: "Velvet lap-sitter",
  },
];
